-- =====================================================
-- BELU - SUPABASE AUDIT
-- Estado MVP actual: auditoria SQL pendiente.
--
-- El archivo anterior tenia triggers de auditoria para el modelo legacy:
-- bookings.beluer_id, assignment_mode y otras columnas antiguas.
-- Se reemplaza por este placeholder para evitar SQL local ejecutable
-- desalineado con la app actual.
--
-- Fase posterior recomendada:
-- - audit_log con actor_profile_id, action, table_name, row_id,
--   old_data, new_data, created_at.
-- - Triggers para:
--   profiles.role
--   beluer_profiles.status / level / is_available
--   services.status / precios
--   bookings.status / beluer_profile_id / payment_status
--   payments.status cuando exista pasarela real
--   beluer_photos.status cuando exista Storage
--
-- No ejecutar auditoria legacy contra el modelo MVP actual.
-- =====================================================
