-- =====================================================
-- BELU - SUPABASE RPC FUNCTIONS
-- Estado MVP actual: sin RPCs activas.
--
-- La app actual implementa operaciones sensibles con Server Actions:
-- - app/actions/client/createBooking.ts
-- - app/actions/client/cancelBooking.ts
-- - app/actions/client/updateClientProfile.ts
-- - app/actions/beluer/updateBeluerBookingStatus.ts
-- - app/actions/beluer/updateBeluerPublicProfile.ts
-- - app/actions/beluer/updateBeluerGoals.ts
-- - app/actions/admin/*
--
-- Esas Server Actions validan sesion/rol/propiedad y usan service_role
-- desde el servidor. Por eso no se definen RPCs activas en este archivo
-- para el MVP actual.
--
-- Las RPCs anteriores dependian del modelo legacy:
-- bookings.client_id, bookings.beluer_id, assignment_mode,
-- booking_services y beluer_services.
-- Se retiraron de este archivo local para evitar documentar SQL ejecutable
-- que ya no coincide con la app.
--
-- Fase posterior:
-- - Culqi/Niubiz/Yape: RPC/webhooks idempotentes de pagos.
-- - WhatsApp/n8n: funciones o jobs de automatizacion.
-- - booking_items: RPC para crear reservas combinadas.
-- - Supabase Storage: RPCs de moderacion de portafolio si aplica.
-- =====================================================
