-- =====================================================
-- BELU - SUPABASE VIEWS
-- Estado MVP actual: sin vistas SQL activas.
--
-- La app actual lee directamente desde Server Components/Server Actions:
-- - app/app/cliente/page.tsx
-- - app/app/beluer/page.tsx
-- - app/app/admin/page.tsx
-- - components/admin-panel-original/*Real*.tsx
--
-- Las vistas anteriores dependian del modelo legacy:
-- booking_services, beluer_services, bookings.client_id,
-- bookings.beluer_id y bookings.assignment_mode.
-- Se retiraron de este archivo local para no dejar vistas ejecutables
-- contra columnas que la app MVP ya no usa.
--
-- Fase posterior:
-- - Reintroducir vistas de lectura si reducen duplicacion real.
-- - Para servicios combinados, basarlas en booking_items.
-- - Para pagos reales, basarlas en payments + webhooks conciliados.
-- =====================================================
