import type {
  AdminAlert,
  AdminBeluer,
  AdminFoto,
  AdminMetricaDistrito,
  AdminMetricaSemana,
  AdminMetricaServicio,
  AdminPago,
  AdminReserva,
  AdminServicio,
} from "./adminPanelTypes";

export const beluersIniciales: AdminBeluer[] = [
  {
    id: "BEL-001",
    nombre: "Andrea Robles",
    instagram: "@andrea.lashes",
    telefono: "+51 987 654 321",
    distrito: "Miraflores",
    servicios: ["Clásicas", "Efecto Rímel", "Volumen 3D", "Lifting"],
    experiencia: 4,
    estado: "aprobada",
    nivel: "Top ✦",
    rating: 5,
    reservas: 120,
    foto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&q=80",
    notaRevision:
      "Portafolio sólido, buena técnica en volumen y acabados naturales.",
  },
  {
    id: "BEL-002",
    nombre: "Camila V.",
    instagram: "@camiv.nails",
    telefono: "+51 955 222 111",
    distrito: "San Isidro",
    servicios: ["Esmaltado Gel", "Rubber", "Softgel", "Clásicas"],
    experiencia: 3,
    estado: "aprobada",
    nivel: "Verificada",
    rating: 4.9,
    reservas: 80,
    foto: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&q=80",
    notaRevision:
      "Perfil mixto interesante. Buena opción para lashes y nails en zonas premium.",
  },
  {
    id: "BEL-003",
    nombre: "Sofía T.",
    instagram: "@sofia.beauty",
    telefono: "+51 944 888 777",
    distrito: "Surco",
    servicios: ["Rubber", "Polygel", "Efecto Aura"],
    experiencia: 2,
    estado: "pendiente",
    nivel: "Nueva",
    rating: 0,
    reservas: 0,
    foto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&q=80",
    notaRevision:
      "Falta validar calidad de portafolio y disponibilidad real en Surco.",
  },
  {
    id: "BEL-004",
    nombre: "Valeria M.",
    instagram: "@valeria.lashpro",
    telefono: "+51 966 111 333",
    distrito: "La Molina",
    servicios: ["Volumen 4D", "Mega Volumen 5D", "Whispy"],
    experiencia: 5,
    estado: "pendiente",
    nivel: "Nueva",
    rating: 0,
    reservas: 0,
    foto: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=300&q=80",
    notaRevision:
      "Buen potencial para servicios premium. Revisar higiene visual del portafolio.",
  },
  {
    id: "BEL-005",
    nombre: "Lucía P.",
    instagram: "@lucia.nailstudio",
    telefono: "+51 999 555 444",
    distrito: "Barranco",
    servicios: ["Acrílicas", "Gel de Construcción", "Pedicura Gel"],
    experiencia: 6,
    estado: "pausada",
    nivel: "Verificada",
    rating: 4.7,
    reservas: 42,
    foto: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&q=80",
    notaRevision:
      "Perfil pausado temporalmente por baja disponibilidad reportada.",
  },
];

export const serviciosIniciales: AdminServicio[] = [
  {
    id: "SRV-001",
    nombre: "Clásicas",
    categoria: "lashes",
    descripcion: "Extensiones una a una para un acabado natural.",
    precioMinimo: 100,
    duracionMinutos: 90,
    activo: true,
  },
  {
    id: "SRV-002",
    nombre: "Efecto Rímel",
    categoria: "lashes",
    descripcion: "Mayor densidad y oscuridad para una mirada intensa.",
    precioMinimo: 110,
    duracionMinutos: 105,
    activo: true,
  },
  {
    id: "SRV-003",
    nombre: "Volumen 3D",
    categoria: "lashes",
    descripcion: "Tres extensiones por pestaña para volumen visible.",
    precioMinimo: 140,
    duracionMinutos: 120,
    activo: true,
  },
  {
    id: "SRV-004",
    nombre: "Lifting de pestañas",
    categoria: "lashes",
    descripcion: "Curva y realce de pestañas naturales sin extensiones.",
    precioMinimo: 100,
    duracionMinutos: 60,
    activo: true,
  },
  {
    id: "SRV-005",
    nombre: "Planchado de cejas",
    categoria: "brows",
    descripcion: "Diseño y fijación de cejas para acabado natural.",
    precioMinimo: 70,
    duracionMinutos: 45,
    activo: true,
  },
  {
    id: "SRV-006",
    nombre: "Esmaltado Gel",
    categoria: "nails",
    descripcion: "Esmalte semipermanente con brillo de gel.",
    precioMinimo: 70,
    duracionMinutos: 60,
    activo: true,
  },
  {
    id: "SRV-007",
    nombre: "Rubber",
    categoria: "nails",
    descripcion: "Base flexible y resistente para uñas naturales.",
    precioMinimo: 85,
    duracionMinutos: 75,
    activo: true,
  },
  {
    id: "SRV-008",
    nombre: "Retiro de gel",
    categoria: "addon",
    descripcion: "Retiro seguro de gel antes de un nuevo servicio.",
    precioMinimo: 25,
    duracionMinutos: 25,
    activo: true,
  },
];

export const reservasIniciales: AdminReserva[] = [
  {
    id: "RSV-001",
    clienta: "María Claudia R.",
    beluer: null,
    servicio: "Efecto Rímel",
    addons: ["Depilación con hilo"],
    distrito: "Miraflores",
    direccion: "Av. Comandante Espinar 456, Miraflores",
    fecha: "2026-05-18",
    hora: "15:30",
    total: 165,
    metodoPago: "Yape",
    estado: "pendiente_asignacion",
    modoAsignacion: "gestionado",
    instrucciones: "Prefiere un acabado natural pero con presencia.",
  },
  {
    id: "RSV-002",
    clienta: "Valeria M.",
    beluer: "Andrea Robles",
    servicio: "Lifting de pestañas",
    addons: [],
    distrito: "San Isidro",
    direccion: "Calle Los Libertadores 220, San Isidro",
    fecha: "2026-05-19",
    hora: "11:00",
    total: 120,
    metodoPago: "Tarjeta",
    estado: "asignada",
    modoAsignacion: "libre",
    instrucciones: "Tiene pestañas sensibles. Llevar materiales suaves.",
  },
  {
    id: "RSV-003",
    clienta: "Lucía P.",
    beluer: "Camila V.",
    servicio: "Rubber",
    addons: ["Retiro de gel"],
    distrito: "Surco",
    direccion: "Av. Primavera 1250, Surco",
    fecha: "2026-05-20",
    hora: "17:00",
    total: 125,
    metodoPago: "Plin",
    estado: "confirmada",
    modoAsignacion: "libre",
    instrucciones: "Prefiere uñas cortas y color nude.",
  },
  {
    id: "RSV-004",
    clienta: "Camila S.",
    beluer: "Sofía T.",
    servicio: "Volumen 3D",
    addons: [],
    distrito: "Barranco",
    direccion: "Jr. Unión 340, Barranco",
    fecha: "2026-05-12",
    hora: "10:00",
    total: 160,
    metodoPago: "Yape",
    estado: "completada",
    modoAsignacion: "gestionado",
    instrucciones: "Quiere efecto más marcado en esquina externa.",
  },
  {
    id: "RSV-005",
    clienta: "Renata G.",
    beluer: null,
    servicio: "Esmaltado Gel",
    addons: [],
    distrito: "La Molina",
    direccion: "Av. La Fontana 890, La Molina",
    fecha: "2026-05-10",
    hora: "16:00",
    total: 85,
    metodoPago: "Tarjeta",
    estado: "cancelada",
    modoAsignacion: "gestionado",
    instrucciones: "Cancelada por solicitud de la clienta.",
  },
];

export const fotosIniciales: AdminFoto[] = [
  {
    id: "FOTO-001",
    beluer: "Andrea Robles",
    categoria: "lashes",
    titulo: "Volumen natural",
    imagen:
      "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=800&q=80",
    estado: "aprobada",
    destacada: true,
    fechaSubida: "2026-05-10",
    notaRevision: "Buena iluminación y resultado limpio.",
  },
  {
    id: "FOTO-002",
    beluer: "Camila V.",
    categoria: "nails",
    titulo: "Rubber nude",
    imagen:
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
    estado: "pendiente",
    destacada: false,
    fechaSubida: "2026-05-16",
    notaRevision: "Revisar nitidez y encuadre antes de aprobar.",
  },
  {
    id: "FOTO-003",
    beluer: "Sofía T.",
    categoria: "lashes",
    titulo: "Efecto Aura",
    imagen:
      "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&q=80",
    estado: "pendiente",
    destacada: false,
    fechaSubida: "2026-05-17",
    notaRevision:
      "Buen resultado, pero falta validar consistencia con el portafolio.",
  },
  {
    id: "FOTO-004",
    beluer: "Valeria M.",
    categoria: "brows",
    titulo: "Brows clean",
    imagen:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80",
    estado: "rechazada",
    destacada: false,
    fechaSubida: "2026-05-12",
    notaRevision: "Imagen no cumple con el estándar visual de belu.",
  },
  {
    id: "FOTO-005",
    beluer: "Lucía P.",
    categoria: "nails",
    titulo: "Acrílicas soft pink",
    imagen:
      "https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800&q=80",
    estado: "aprobada",
    destacada: false,
    fechaSubida: "2026-05-08",
    notaRevision: "Buen acabado, imagen usable para catálogo.",
  },
];

export const pagosIniciales: AdminPago[] = [
  {
    id: "PAY-001",
    reservaId: "RSV-001",
    clienta: "María Claudia R.",
    beluer: "Sin asignar",
    servicio: "Efecto Rímel + Depilación con hilo",
    fecha: "2026-05-18",
    metodo: "Yape",
    proveedor: "Manual",
    estado: "pagado",
    monto: 165,
    comisionBelu: 25,
    netoBeluer: 140,
    operacion: "YP-884219",
  },
  {
    id: "PAY-002",
    reservaId: "RSV-002",
    clienta: "Valeria M.",
    beluer: "Andrea Robles",
    servicio: "Lifting de pestañas",
    fecha: "2026-05-19",
    metodo: "Tarjeta",
    proveedor: "Culqi",
    estado: "pagado",
    monto: 120,
    comisionBelu: 18,
    netoBeluer: 102,
    operacion: "CQ-193820",
  },
  {
    id: "PAY-003",
    reservaId: "RSV-003",
    clienta: "Lucía P.",
    beluer: "Camila V.",
    servicio: "Rubber + Retiro de gel",
    fecha: "2026-05-20",
    metodo: "Plin",
    proveedor: "Manual",
    estado: "pendiente",
    monto: 125,
    comisionBelu: 19,
    netoBeluer: 106,
    operacion: "PL-552901",
  },
  {
    id: "PAY-004",
    reservaId: "RSV-004",
    clienta: "Camila S.",
    beluer: "Sofía T.",
    servicio: "Volumen 3D",
    fecha: "2026-05-12",
    metodo: "Yape",
    proveedor: "Manual",
    estado: "pagado",
    monto: 160,
    comisionBelu: 24,
    netoBeluer: 136,
    operacion: "YP-441820",
  },
  {
    id: "PAY-005",
    reservaId: "RSV-005",
    clienta: "Renata G.",
    beluer: "Sin asignar",
    servicio: "Esmaltado Gel",
    fecha: "2026-05-10",
    metodo: "Tarjeta",
    proveedor: "Niubiz",
    estado: "reembolsado",
    monto: 85,
    comisionBelu: 0,
    netoBeluer: 0,
    operacion: "NB-991270",
  },
  {
    id: "PAY-006",
    reservaId: "RSV-006",
    clienta: "Daniela F.",
    beluer: "Lucía P.",
    servicio: "Acrílicas",
    fecha: "2026-05-09",
    metodo: "Tarjeta",
    proveedor: "Culqi",
    estado: "fallido",
    monto: 135,
    comisionBelu: 0,
    netoBeluer: 0,
    operacion: "CQ-FAILED-028",
  },
];

export const serviciosTopIniciales: AdminMetricaServicio[] = [
  {
    nombre: "Efecto Rímel",
    categoria: "lashes",
    reservas: 18,
    ingresos: 2160,
  },
  {
    nombre: "Rubber",
    categoria: "nails",
    reservas: 14,
    ingresos: 1260,
  },
  {
    nombre: "Lifting de pestañas",
    categoria: "lashes",
    reservas: 12,
    ingresos: 1320,
  },
  {
    nombre: "Volumen 3D",
    categoria: "lashes",
    reservas: 10,
    ingresos: 1600,
  },
  {
    nombre: "Esmaltado Gel",
    categoria: "nails",
    reservas: 9,
    ingresos: 675,
  },
];

export const distritosTopIniciales: AdminMetricaDistrito[] = [
  {
    distrito: "Miraflores",
    reservas: 22,
    ingresos: 2860,
  },
  {
    distrito: "San Isidro",
    reservas: 18,
    ingresos: 2340,
  },
  {
    distrito: "Surco",
    reservas: 15,
    ingresos: 1950,
  },
  {
    distrito: "La Molina",
    reservas: 9,
    ingresos: 1080,
  },
  {
    distrito: "Barranco",
    reservas: 7,
    ingresos: 820,
  },
];

export const semanasIniciales: AdminMetricaSemana[] = [
  {
    semana: "Semana 1",
    reservas: 12,
    ingresos: 1460,
  },
  {
    semana: "Semana 2",
    reservas: 18,
    ingresos: 2240,
  },
  {
    semana: "Semana 3",
    reservas: 21,
    ingresos: 2680,
  },
  {
    semana: "Semana 4",
    reservas: 26,
    ingresos: 3180,
  },
];

export const adminAlerts: AdminAlert[] = [
  {
    title: "3 Beluers pendientes de aprobación",
    text: "Revisa sus perfiles, experiencia, zonas y portafolio antes de activarlas.",
    action: "Revisar Beluers",
    section: "beluers",
  },
  {
    title: "5 fotos pendientes de validación",
    text: "Las fotos nuevas deben aprobarse antes de aparecer en el catálogo público.",
    action: "Validar fotos",
    section: "fotos",
  },
  {
    title: "2 reservas necesitan seguimiento",
    text: "Hay reservas gestionadas que aún no tienen Beluer asignada.",
    action: "Ver reservas",
    section: "reservas",
  },
];