import type {
  IngresoBeluer,
  PerfilBeluer,
  ReservaBeluer,
} from "./beluerPanelTypes";

export const reservasIniciales: ReservaBeluer[] = [
  {
    id: "BLU-RSV-001",
    clienta: "María Claudia R.",
    servicio: "Efecto Rímel + Depilación con hilo",
    distrito: "Miraflores",
    direccion: "Av. Comandante Espinar 456, Miraflores",
    fecha: "2026-05-18",
    hora: "15:30",
    total: 165,
    estado: "pendiente",
    instrucciones: "Prefiere un acabado natural pero con más presencia.",
    metodoPago: "Yape",
  },
  {
    id: "BLU-RSV-002",
    clienta: "Valeria M.",
    servicio: "Lifting de pestañas",
    distrito: "San Isidro",
    direccion: "Calle Los Libertadores 220, San Isidro",
    fecha: "2026-05-19",
    hora: "11:00",
    total: 120,
    estado: "pendiente",
    instrucciones: "Tiene pestañas sensibles. Llevar materiales suaves.",
    metodoPago: "Tarjeta",
  },
  {
    id: "BLU-RSV-003",
    clienta: "Lucía P.",
    servicio: "Volumen 3D",
    distrito: "Surco",
    direccion: "Av. Primavera 1250, Surco",
    fecha: "2026-05-20",
    hora: "17:00",
    total: 160,
    estado: "aceptada",
    instrucciones: "Quiere efecto más marcado en la esquina externa.",
    metodoPago: "Plin",
  },
  {
    id: "BLU-RSV-004",
    clienta: "Camila S.",
    servicio: "Planchado de cejas",
    distrito: "Barranco",
    direccion: "Jr. Unión 340, Barranco",
    fecha: "2026-05-21",
    hora: "10:00",
    total: 90,
    estado: "aceptada",
    instrucciones: "Prefiere cejas naturales, no muy marcadas.",
    metodoPago: "Yape",
  },
];

export const ingresosIniciales: IngresoBeluer[] = [
  {
    id: "ING-001",
    fecha: "2026-05-18",
    clienta: "María Claudia R.",
    servicio: "Efecto Rímel + Depilación con hilo",
    totalServicio: 165,
    comisionBelu: 25,
    netoBeluer: 140,
    estadoPago: "pendiente",
  },
  {
    id: "ING-002",
    fecha: "2026-05-17",
    clienta: "Lucía P.",
    servicio: "Volumen 3D",
    totalServicio: 160,
    comisionBelu: 24,
    netoBeluer: 136,
    estadoPago: "pagado",
  },
  {
    id: "ING-003",
    fecha: "2026-05-14",
    clienta: "Valeria M.",
    servicio: "Lifting de pestañas",
    totalServicio: 120,
    comisionBelu: 18,
    netoBeluer: 102,
    estadoPago: "pagado",
  },
  {
    id: "ING-004",
    fecha: "2026-05-10",
    clienta: "Camila S.",
    servicio: "Planchado de cejas",
    totalServicio: 90,
    comisionBelu: 14,
    netoBeluer: 76,
    estadoPago: "retenido",
  },
];

export const perfilInicial: PerfilBeluer = {
  nombrePublico: "Andrea Robles",
  bio: "Especialista en extensiones de pestañas, lifting y diseño de cejas. Trabajo con acabados naturales, limpios y de larga duración.",
  instagram: "@andrea.lashes",
  whatsapp: "+51 987 654 321",
  experiencia: 4,
  nivel: "Beluer Top ✦",
  estado: "Activo",
  distritos: ["Miraflores", "San Isidro", "Surco"],
  disponibilidadGeneral: true,
};
